---

version: '3'

services:
  exercises:
    build:
      context: ../../Downloads/exercises-java-master
      dockerfile: Dockerfile
    volumes:
      - .:/exercises-java
    command: make lint test
